##############################################################################
#
# File: student.S
#
# Description:
#   This file contains skeleton source code that students should complete so
#   that it performs the computations required in the Machine Problem handout.
#
##############################################################################

.text

/*
 * Function: findHypSq
 *
 * Description:
 *  <WRITE DESCRIPTION HERE>
 *
 * Inputs:
 *  %rdi - <WRITE DESCRIPTION HERE>
 *
 * Return value:
 *  %rax - <WRITE DESCRIPTION HERE>
 *
 */
.global findHypSq
.type findHypSq, @function
findHypSq:
  /*
   * Insert your commented code here.
   */
  retq

/*
 * Function: ratios
 *
 * Description:
 *  <WRITE DESCRIPTION HERE>
 *
 * Inputs:
 *  <WRITE DESCRIPTIONS OF INPUTS HERE>
 *
 * Return value:
 *  %rax - <WRITE DESCRIPTION OF RETURN VALUE HERE>
 */
.global ratios
.type ratios, @function
ratios:
  /*
   * Insert your commented code here.
   */
  retq

/*
 * Function: removeCard
 *
 * Description:
 *  WRITE DESCRIPTION OF WHAT FUNCTION DOES HERE.
 *
 * Inputs:
 *  <WRITE DESCRIPTIONS OF INPUTS HERE>
 *
 * Return value:
 *  %rax - <WRITE DESCRIPTION OF RETURN VALUE HERE>
 */
.global removeCard
.type removeCard, @function
removeCard:
  /*
   * Insert your commented code here.
   */
  retq
